const jobDetails = [
  {
    period: "Jan 2022 - Present",
    location: "Bangalore, IN",
    title: "Senior Frontend Engineer - Capillary Technologies",
    responsibilities: [
      "Improved development efficiency by 60% through meticulous planning and technical guidance, reducing the product lifecycle from 3 to 2 quarters.",
      "Implemented dynamic micro-frontends with React, decreasing integration time by 40% and boosting system performance.",
      "Mentored new team members, cutting ramp-up time by 40%, while leading end-to-end development, achieving 99.99% system uptime.",
      "Utilized NewRelic for monitoring, decreasing error rate by 30%, and implemented proactive monitoring with WebdriverIO.",
      "Optimized data management with React and Redux, reducing data save time by 90%.",
      "Employed Test-Driven Development (TDD) with Jest and RTL, enhancing code reliability and reducing errors.",
      "Developed a LoopBack 4 API middleware extension to integrate custom logic, handling domain-specific tasks (e.g., hospitality, airlines) before core API transactions. Delivered 300% of the expected outcome, enhancing flexibility without altering core functions.",
      "Worked on user and organization-level RBAC (Role-Based Access Control) implementation, ensuring robust access management.",
      "Implemented configuration-based UI, hiding or showing tabs, widgets based on organization config, enhancing user experience and customization.",
      "Received multiple spot awards for accountability and excellence in task execution.",
    ],
    skills: [
      "React",
      "Redux",
      "Jest",
      "TDD",
      "LoopBack",
      "NewRelic",
      "WebdriverIO",
      "Grafana",
      "Bash",
      "MySQL",
      "Javascript",
      "Typescript",
      "PHP",
      "CSS",
      "Mongoose",
      "Jest",
      "React Testing Library",
      "Kubernetes",
      "Bugsnag",
      "Full Story",
      "Babel",
      "Webpack",
      "Redis",
      "Git",
    ],
  },
  {
    period: "July 2021 - April 2022",
    location: "Mangalore, IN",
    title: "Software Engineer 1 - CodeCraft Technologies",
    responsibilities: [
      "Architected and implemented the backend for ECG reports using NestJS and MongoDB, ensuring high code reliability and maintainability through TDD.",
      "Developed robust and scalable APIs, mentoring team members on performance optimizations and best practices.",
    ],
    skills: [
      "NestJS",
      "MongoDB",
      "TDD",
      "Javascript",
      "Typescript",
      "AWS",
      "Git",
    ],
  },
  {
    period: "July 2019 - July 2021",
    location: "Mangalore, IN",
    title: "Software Engineer 1 - Juego Studios Private Limited",
    responsibilities: [
      "Designed and developed highly scalable server applications for multiplayer games, chat, and real-time applications.",
      "Organized tasks efficiently, contributing ideas and suggestions in team meetings, and delivering updates on deadlines and enhancements.",
      "Implemented App Store in-app purchase verification and fixed heap out-of-memory issues in legacy codebases, improving system stability and performance.",
      "Developed real-time and turn-based gaming applications using NodeJS, Serverless, and PHP.",
      "Notable Projects: NodeJS: Kalutai, Earth Arena, SOA, MCL Poker, GamesApp Poker Engine. Serverless: NOMOS, Teenpatti, Burraco Italiano, Configurable Card-Game Engine (PokerMaster). PHP: Earth Arena, SOA. Configurable Card Game Engine (PokerMaster): Supported poker variants with serverless API, WebSocket, MySQL, and Redis.",
    ],
    skills: [
      "NodeJS",
      "Serverless",
      "PHP",
      "WebSocket",
      "MySQL",
      "Redis",
      "AWS EC2",
      "AWS Lambda",
      "AWS API Gateway",
      "Javascript",
      "Typescript",
      "Python",
      "Docker",
      "Git",
      "Mysql",
      "Mongoose",
      "Nginx",
      "Apache2",
    ],
  },
];

export default jobDetails;
