const jobDetails = [
  {
    period: "September 2024 - Present",
    location: "Bengaluru, IN",
    title: "Senior Engineering Lead – Frontend, Persistent Systems",
    responsibilities: [
      "Led frontend development using React.js, Next.js, React-Query, TailwindCSS, React Hook Form, and TypeScript.",
      "Collaborated with cross-functional teams to design and implement scalable solutions on AWS Cloud.",
      "Enhanced user experiences and optimized application performance while maintaining high code quality.",
      "Implemented a chatbot UI for the LOR project, enabling seamless task execution and answers for users.",
      "Fostered team productivity and delivered high-quality solutions under tight deadlines.",
    ],
    skills: [
      "React.js",
      "Next.js",
      "React-Query",
      "TailwindCSS",
      "React Hook Form",
      "TypeScript",
      "AWS",
      "Node.js",
    ],
  },
  {
    period: "September 2022 - August 2024",
    location: "Bengaluru, IN",
    title: "Software Engineer 2 – Frontend, Capillary Technologies",
    responsibilities: [
      "Increased development efficiency by 60% through agile methodologies and automation tools.",
      "Developed dynamic micro-frontends using React, reducing integration time by 40%.",
      "Mentored new engineers, decreasing ramp-up time by 40%, and led projects with 99.99% uptime.",
      "Implemented monitoring solutions with New Relic and Selenium, reducing error rates by 30%.",
      "Enhanced security by designing and implementing user and organization-level RBAC systems.",
      "Created a configuration-based UI, improving user satisfaction by 40% within three months.",
    ],
    skills: [
      "React.js",
      "Redux",
      "Jest",
      "React Testing Library",
      "New Relic",
      "TypeScript",
      "Selenium",
      "CI/CD",
      "MongoDB",
      "MySQL",
    ],
  },
  {
    period: "September 2021 - August 2022",
    location: "Bengaluru, IN",
    title: "Software Engineer – Frontend, Codecraft Technologies",
    responsibilities: [
      "Developed backend architecture for ECG reports using NestJS and MongoDB.",
      "Implemented frontend UI using ReactJS with TDD practices.",
      "Created scalable APIs and mentored team members on performance optimization.",
      "Improved user satisfaction scores by 35% through caching strategy optimization.",
    ],
    skills: [
      "NestJS",
      "MongoDB",
      "React.js",
      "TypeScript",
      "JavaScript",
      "TDD",
    ],
  },
  {
    period: "July 2019 - September 2021",
    location: "Bengaluru, IN",
    title: "Software Engineer – Frontend, Juego Studios",
    responsibilities: [
      "Designed scalable server applications for multiplayer games, chat, and real-time apps.",
      "Developed real-time and turn-based gaming applications using Node.js and PHP.",
      "Created a configurable card game engine (Poker Master) using serverless architecture.",
      "Contributed to projects like Kalutai, Earth Arena, SOA, MCL Poker, and GamesApp Poker Engine.",
    ],
    skills: [
      "Node.js",
      "Serverless",
      "React.js",
      "WebSocket",
      "Redis",
      "MySQL",
      "PHP",
      "TDD",
    ],
  },
  {
    period: "December 2017 - March 2019",
    location: "Bengaluru, IN",
    title: "Software Engineer, Fiverr",
    responsibilities: [
      "Collaborated with diverse clients to develop robust web applications using C# and React.js.",
      "Automated workflows with Python and Selenium, improving efficiency.",
      "Delivered client-focused solutions adhering to timelines and specifications.",
    ],
    skills: [
      "React.js",
      "C#",
      "Python",
      "Selenium",
      "JavaScript",
    ],
  },
];

export default jobDetails;
