# Workflow to build and deploy to the root of gh-pages branch
name: Build and Deploy to gh-pages

on:
  # Trigger on pushes to the master branch
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies and build the project
      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      # Step 3: Deploy the contents of the dist folder to the gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist # The dist folder is uploaded to the root of gh-pages
          publish_branch: gh-pages # Target branch for deployment
