# Workflow to deploy static content to the gh-pages branch
name: Deploy static content to gh-pages

on:
  # Trigger on pushes to the default branch
  push:
    branches: ["master"]

  # Allows the workflow to be run manually
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install dependencies and build (if required)
      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build # Replace this with your project's build command, if needed

      # Deploy the dist folder to gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist # Path to the folder to deploy
          publish_branch: gh-pages # Target branch for deployment
